### ISSUE TITLE
Misleading and hard to use error messages

### ISSUE THREAD

**Issue by ReneSac** [nim-lang/nimforum#195]
In the following message 
```
Thanks for all answers and sorry for the late reply.

At first I tried creating new overloads semi-ignored the HSlice problem. Semi-ignored because now the '..' and related operators from system always return a HSlice instead of a slice, even if both sides are regular indexes. So I changed the type to accept HSlice[SomeInteger, SomeInteger], but not the implementation. This satisfied me for a while, but now I came back to implement the BackwardsIndex for slices and the previous overload solution simply doesn`t scale well. I then used jypayne link to see how that change was made in the standard library, and found the `^^` helper template, that is indeed very useful.

..code-block:: nim
	type SomeIndex = SomeInteger | BackwardsIndex

	template `^^`(s, i: untyped): untyped =
	  (when i is BackwardsIndex: s.len - int(i) else: int(i))

Using them updating the functions is just a matter of updating the index/bounds type and prepending `s^^` (or whatever the name of your first argument) to every use of the index/bounds type. No overloading needed, just two functions for indexing (and one for slicing):

```

The forum gives the error:

```input(7, 18) Error: '`' expected```

In the preview window. W/o experience, it took me several minutes to correct it.

Besides the error being about the wrong thing, it cites a line and a column, and there is neither line nor column indications in the editing window. It is even more annoying because when switching back and forth between the preview and the editing views, the forum won't remember the size of the editing box, that unlike github doesn't resize automatically with the text size either. It remains in it's default too small size.

By the way, while a preview is an advancement, I much preferred the old forum software, with pages, functional w/o javascript, better styling IMHO, etc. It's also ugly and unintuitive the way to go back to the main page of the forum, IMHonestO. Some text would help.

**Comment by jyapayne** [comment]
That is a misleading error. Really, it should say something like what it says if you try to hit the reply button, ie: "Message needs to be valid RST". Ideally it would also give an accurate location of the error, but that's a bit difficult in this situation because it's unclear to the parser whether or not you intended to put a (**`**) or not. I can change the exception message to be at least as clear as the reply button's message.

Your issue about the edit box not resizing and how the forum doesn't remember the size is a valid concern as well, since I'm sure you're not the only one who has these issues. It's very useful feedback that will make the forum a better app, so thank you.

> By the way, while a preview is an advancement, I much preferred the old forum software, with pages, functional w/o javascript, better styling IMHO, etc. It's also ugly and unintuitive the way to go back to the main page of the forum, IMHonestO. Some text would help.

The old forum was very nice, yes, but hopefully with some work this new forum will become much better and easier to use. New things tend to be rough around the edges at first but hopefully you'll come to enjoy some of the features we have planned like categories/tags, sorting/filtering, notifications, and sticky threads. And of course fixing the little convenience issues like these.

I agree that it could be made clearer how to get back to the main page. Maybe a little link/button at the top of the thread that says "< Back to Main Page". Would that help?

**Comment by jyapayne** [comment]
@dom96 I understand your point of view. However, there's nothing that separates the Nim forum logo from the regular Nim logo. So at first I thought the Nim logo would take me back to the main page http://nim-lang.org and I was confused on how to get back to the main forum page, much like @ReneSac is/was. In Github/Discourse/etc this works because there is only one page to possibly to back to based on the logo, but here it's a bit ambiguous.

Maybe the "back to main page" button is a little overzealous, but then instead maybe we could make a different logo for the forum?

**Comment by dom96** [comment]
If we can get a nice logo for the forum then sure, but from what I've seen many Discourse forums use the same logo, for example: [Rust](http://users.rust-lang.org/), and [Julia](https://discourse.julialang.org/)

**Comment by jyapayne** [comment]
Hmm, it seems you're right. Maybe I'm just a bit too old fashioned. It does look really nice and clean the way it is. For the logo, I was thinking something similar to the logo on the main nim page, but with "forum" added at the end. Kind of lame, but clear. Anyways, I don't think it's a super big deal since the back button works and so does navigation with Alt+Arrow keys.

**Comment by ReneSac** [comment]
I don't see anything I complained tackled... The merged change referenced here maintains the misleading error and adds an obvious message to it that makes no difference IMHO: I know it is invalid in some way, as you aren't even trying to render it and wont accept for posting! Removing the error message altogether might help this particular case, but I would hope those error messages usually help rather than hinder finding the error, so not a good solution either... Is this closed as won't fix?


> If we can get a nice logo for the forum then sure, but from what I've seen many Discourse forums use the same logo, for example: Rust, and Julia

Well, I also consider those two examples pretty ugly and unintuitive... I like traditional phpBB and vBulletin style forums. Those you point have so much blank space, faint or non-existent columns and lines dividing things, etc. This github page, for example, is much better in all those accounts IMHO, and has a clearly named button to go back to the list of issues.

Another reason I don't like the new style of Nim forum is that you have a big empty boring rectangular black bar on the top, with only a small simple logo on one corner, with no title saying "Nim's Forum" or something like that.

Well, it's all personal opinion I guess.

> It's a common convention to use a logo to mean "front page" (GitHub, Discourse, etc. all use this).

Nim's front-page is `https://nim-lang.org/`. AFAIK there is no link to go back to it once you click the "Forum" (a properly named hyperlink) on the top bar. The same once you enter some documentation page, for example. This is also something that has always bothered me.

**Comment by jyapayne** [comment]
> I don't see anything I complained tackled... The merged change referenced here maintains the misleading error and adds an obvious message to it that makes no difference IMHO: I know it is invalid in some way, as you aren't even trying to render it and wont accept for posting! Removing the error message altogether might help this particular case, but I would hope those error messages usually help rather than hinder finding the error, so not a good solution either... Is this closed as won't fix?

@ReneSac the title of your issue is "Misleading and hard to use error message". I thought the main issue was for the error message, no? It's common practice in git/github to file one issue per thing that needs to be changed, so it's clear what needs to be fixed and the Github issue doesn't turn into a really big project. In my opinion, there are really 3 issues in this one issue:

1. Error message doesn't say what was wrong
2. Hard to debug line/column number without line & column in edit window
3. Size of editing box is not remembered when switching from preview to edit and back

The first one is easy, which I fixed and is part of the title of this issue. The second issue is probably much more work and definitely deserves it's own issue, which you can feel free to make as a feature request. The third is probably not super complicated, but still deserves it's own issue as a feature request/bug depending on how you look at it, which you can also feel free to submit :)

> All forums I know, IIRC, render anything you write, and if you make an error the rendering is broken from that error onwards but it is there and this usually helps finding the error faster. Just an idea.

This is an idea that I had as well but the current rstToHtml implementation in Nim needs to be either reworked or another proc needs to be written for that to happen so that it doesn't throw an error when it hits invalid RST. That should be an issue on the main Nim repo.

**Comment by ReneSac** [comment]
Yeah, sorry, it should really have been split into multiple issues. Well, it is true that the error message now says what is wrong, but what follows is still equally misleading so I don't seem any real change regarding 1. 

I'm not sure if number 2 should be sought after, as changing the rtsToHtml would get rid of the issues 1 and 2 in a more elegant way. But I will not fill that issue in Nim main repo, as I'm not the one using the API, so I don't know well how to ask.

I will open a feature request for number 3.

**Comment by jyapayne** [comment]
I filed an issue for the rstToHtml function. Hopefully that change will make things a bit more friendly. Thank you for filing the issue for number 3.

**Comment by ReneSac** [comment]
Just a final note: if it wasn't clear, the actual error in my example message was the missing space between ".." and "code-block". Of course, that alone doesn't make the RST invalid, and what stopped the parser was the perceived missing \`.
