### ISSUE TITLE
nim forum fails to load on firefox, works on brave

### ISSUE THREAD

**Issue by noahehall** [nim-lang/nimforum#350]
### Description

try to load any thread, e.g. [the version 2 releaase thread](https://forum.nim-lang.org/t/10366)

![image](https://github.com/nim-lang/Nim/assets/10324554/420560c3-104a-49cb-a6ac-d5b9ee0b8923)

works in brave and chromium

### Nim Version

n/a

**Comment by geotre** [comment]
Most likely the result of [this issue](https://github.com/karaxnim/karax/issues/232) where Karax would fail if extensions modified the dom. This was fixed in [this PR](https://github.com/karaxnim/karax/pull/234) which was updated for the forum in [this PR](https://github.com/nim-lang/nimforum/pull/335) on 2022-12-23, but the forum hasn't been deployed since 2022-10-01 (you can see in the html returned).

@Araq who is able to deploy new versions to the forum server at the moment? If nobody is interested, I volunteer to do it.

Also if you add me to this repo, I will try to clean up some of the issue/PR backlog

**Comment by geotre** [comment]
CC @ringabout , any idea about the server?

**Comment by ringabout** [comment]
> any idea about the server?

Sorry, I don't have access to the server. I have posted the issue to the moderator channel. Hopefully, it could be deployed as soon as possible.

**Comment by geotre** [comment]
@ringabout just chasing this, it looks like the deployed forum is the same version. Any news?

Please can you forward the message to the moderator group that I am willing to handle deployments of the server so that we can unblock fixes?

**Comment by ringabout** [comment]
Definitely, I have posted the message to the moderator channel. I'm sorry that I cannot help much. Thanks very much for informing us of the outdated deployment!

**Comment by ringabout** [comment]
@geotre a new version has been deployed!
