### ISSUE TITLE
Forum seems vulnerable to CSRF

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/nimforum#79]
There are no [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery) token used.

**Comment by dom96** [comment]
Can you give an example of what you think is vulnerable?

**Comment by zielmicha** [comment]
For example, if we get someone to visit out page, let's say http://evil.com, we can place a form which is identical to the one on new thread page:

```
 <form action="http://forum.nim-lang.org/donewthread" method="POST">
      <input type="text" name="subject" maxlength="100" value="evil evil evil" />
      <br />
    <textarea name="content">evil evil evil</textarea><br />
    <input type="hidden" name="threadid" value="-1" />
            <input type="hidden" name="postid" value="-1" />
    <input type="submit" name="previewBtn" value="Preview" />
    <input type="submit" name="postBtn" value="Submit" />
```
And autosubmit it via Javascript in iframe (or simply get user to submit it manually by imitating some other form). We have a topic with content created by use in name of other user. 
We can use the same technique to, for example, ban users if we get admin to visit a page controlled by us.

**Comment by dom96** [comment]
Modern websites nowadays support the ``SameSite`` directive which fixes this security issue. I decided to adopt it instead of coming up with a CSRF token scheme. For our use cases it should be good enough.

https://caniuse.com/same-site-cookie-attribute

Implemented in Jester here: https://github.com/dom96/jester/commit/64295c8a06efff275344ccf88dd7df38d321dd74
